/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ross
 */
public class View extends javax.swing.JPanel {
    SearchableObject objectToShow;
    String show;
    
    /**
     * Creates new form View
     */
    public View(SearchableObject objectToShow) {
        this.objectToShow = objectToShow;
                
        switch(objectToShow.getType().toString()){
            case("CAR"):{
                Car car = (Car) objectToShow;
                
                show = String.format(
                        "%s %s %s"
                        + "Number of miles: %s\n"
                        + "Registraton: %s\n"
                        + "Price: £%s </html>",
                        car.getColour(), car.getMake(), car.getModel(),
                        car.getNumberOfMiles(), car.getReg(), car.getPrice());
                
                break;
            }
            
            case("EMPLOYEE"):{
                Employee employee = (Employee) objectToShow;
                
                show = employee.getDepartment();
                
                break;
            }
            
            case("CUSTOMER"):{
                Customer customer = (Customer) objectToShow;
                
                show = customer.getFavouriteCarMake();
                
                break;
            }
        }
        
        // work out the secret type
        
        
        
        
        /* LEGACY
         Field[] attributes = selected.getClass().getDeclaredFields();
        
        for(Field field: attributes) {
            System.out.print(field.getName());
            
            try {
               PropertyUtils.setSimpleProperty(selected, field.getName(), "value");
               Object value = PropertyUtils.getSimpleProperty(selected, field.getName());
               System.out.println(value.toString());
            } catch (Exception e) {
               e.printStackTrace();
            }
        } */
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        backToMenu = new javax.swing.JButton();

        jLabel1.setText("View");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(show);
        jScrollPane2.setViewportView(jTextArea1);

        backToMenu.setText("←");
        backToMenu.setMargin(new java.awt.Insets(2, 1, 2, 1));
        backToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backToMenu))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backToMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton backToMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
