public class View extends javax.swing.JPanel {
    SearchableObject objectToShow;
    String show;

    /**
     * Creates a JPanel of a view page for the object that it is constructed with
     *  - Can be constructed with anything that extends searchableObject
     *  - Type matching is done through Type enum
     * @param objectToShow - SearchableObject object that will be shown
     */
    public View(SearchableObject objectToShow) {
        this.objectToShow = objectToShow;

        switch(objectToShow.type.toString()){
            case("CAR"):{
                Car car = (Car) objectToShow;

                show = String.format(
                        "%s %s %s \n"
                        + "Number of miles: %s\n"
                        + "Registraton: %s\n"
                        + "Price: £%s",
                        car.getColour(), car.getMake(), car.getModel(),
                        car.getNumberOfMiles(), car.getReg(), car.getPrice());

                break;
            }

            case("EMPLOYEE"):{
                Employee employee = (Employee) objectToShow;

                show = String.format(
                        "%s %s \n"
                        + "Salary: %s \n"
                        + "Department: %s \n"
                        + "Username: %s \n"
                        + "%s's password is not displayed for security purposes",
                        employee.getFirstName(), employee.getLastName(),
                        employee.getSalary(),  employee.getDepartment(),
                        employee.getUserName(), employee.getFirstName()
                );

                break;
            }

            case("CUSTOMER"):{
                Customer customer = (Customer) objectToShow;

                show = String.format(
                        "%s %s \n"
                        + "Favourite car make: %s \n",
                        customer.getFirstName(), customer.getLastName(),
                        customer.getFavouriteCarMake()
                );

                break;
            }
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        backToMenu = new javax.swing.JButton();

        jLabel1.setText("View");

        jScrollPane2.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(show);
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(null);
        jScrollPane2.setViewportView(jTextArea1);

        backToMenu.setText("←");
        backToMenu.setMargin(new java.awt.Insets(2, 1, 2, 1));
        backToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(backToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backToMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backToMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton backToMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
